name: questPlugin
version: '1.0'
main: me.kwilver.questPlugin.QuestPlugin
api-version: '1.21'
depend: [ProtocolLib]
commands:
  debugQuest:
    permission: op
  questInfo:

  #glyphdebug:
  #  permission: op
  SummonOracle:
    permission: op
  EquipGlyph:
    permission: op
  GlyphManager:
    permission: op
  enablequest:
    permission: op
  disablequest:
    permission: op
  GlyphLoadout:
    permission: op
  UseGlyph:

  acceptChallenge:

  declineChallenge:

  remove:
    permission: op



